//! Headless browser backend over the Chrome DevTools Protocol (chromiumoxide).
//!
//! `BrowserBackend` wraps a headless Chromium and exposes operations that map
//! directly onto Phantom's neutral action vocabulary (navigate, click, type,
//! extract, screenshot). Each [`execute`](BrowserBackend::execute) call returns
//! a fresh screenshot + page snapshot so the agent loop can observe state.

use chromiumoxide::browser::{Browser, BrowserConfig, HeadlessMode};
use chromiumoxide::detection;
use chromiumoxide::layout::Point;
use chromiumoxide::page::ScreenshotParams;
use futures::StreamExt;
use phantom_proto::ActionResponse;
use std::path::PathBuf;
use tokio::task::JoinHandle;

use crate::actions::ActionResult;

/// Resolve the Chromium/Chrome executable to use.
///
/// Precedence:
/// 1. `PHANTOM_CHROME` / `CHROME` environment overrides (explicit path).
/// 2. chromiumoxide's PATH/registry detection.
///
/// On Linux, `/snap/bin/chromium` is a symlink to `/usr/bin/snap`. When
/// chromiumoxide launches it via `async_process`, the symlink is resolved for
/// `argv[0]`, so `snap` interprets our Chromium flags as its *own* CLI flags and
/// aborts ("unknown flag ..."). We detect that case and substitute a tiny
/// generated wrapper that execs `snap run chromium` (correct `argv[0]`), so the
/// flags are forwarded to the browser. Returns `None` when no browser is found
/// at all — callers should skip gracefully in that case.
fn resolve_chrome_executable() -> anyhow::Result<Option<PathBuf>> {
    for env in ["PHANTOM_CHROME", "CHROME"] {
        if let Ok(p) = std::env::var(env) {
            if !p.trim().is_empty() {
                return Ok(Some(PathBuf::from(p.trim())));
            }
        }
    }

    match detection::default_executable(detection::DetectionOptions::default()) {
        Ok(exe) if is_snap_symlink(&exe) => Ok(Some(snap_wrapper()?)),
        Ok(exe) => Ok(Some(exe)),
        Err(_) => Ok(None),
    }
}

#[cfg(target_os = "linux")]
fn is_snap_symlink(exe: &std::path::Path) -> bool {
    let s = exe.to_string_lossy();
    if s.contains("/snap/bin/") {
        return true;
    }
    if let Ok(target) = std::fs::read_link(exe) {
        let t = target.to_string_lossy();
        return t == "/usr/bin/snap" || t.ends_with("/snap");
    }
    false
}

#[cfg(not(target_os = "linux"))]
fn is_snap_symlink(_exe: &std::path::Path) -> bool {
    false
}

/// Generate (once) and return a wrapper script that drives snap Chromium.
#[cfg(target_os = "linux")]
fn snap_wrapper() -> anyhow::Result<PathBuf> {
    let dir = std::env::temp_dir().join("phantom-chromium");
    std::fs::create_dir_all(&dir)?;
    let wrapper = dir.join("chromium-snap-wrapper.sh");
    if !wrapper.exists() {
        std::fs::write(
            &wrapper,
            "#!/bin/sh\n# Generated by Phantom: drive snap Chromium from async_process.\n\
             exec /usr/bin/snap run chromium \"$@\"\n",
        )?;
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&wrapper)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&wrapper, perms)?;
    }
    Ok(wrapper)
}

#[cfg(not(target_os = "linux"))]
fn snap_wrapper() -> anyhow::Result<PathBuf> {
    anyhow::bail!("snap wrapper is only supported on Linux")
}

/// A headless Chromium session driven over CDP.
pub struct BrowserBackend {
    browser: Browser,
    page: chromiumoxide::Page,
    _handler: JoinHandle<()>,
}

impl BrowserBackend {
    /// Launch a headless Chromium and open a blank page.
    ///
    /// We deliberately call [`BrowserConfigBuilder::disable_default_args`] and
    /// supply a curated, widely-compatible argument set. chromiumoxide 0.6.0's
    /// built-in `DEFAULT_ARGS` includes flags (e.g. `--disable-background-
    /// networking`) that newer Chromium builds — including the snap-packaged
    /// Chromium 150 on Linux — reject with "unknown flag", which aborts launch.
    /// With default args disabled, chromiumoxide still auto-injects the
    /// essential flags (`--remote-debugging-port`, `--user-data-dir`,
    /// `--no-sandbox`/`--disable-setuid-sandbox`, and the headless flags), so
    /// the connection works while we stay in control of the rest.
    pub async fn launch() -> anyhow::Result<Self> {
        let mut builder = BrowserConfig::builder()
            .headless_mode(HeadlessMode::New)
            .disable_default_args()
            .no_sandbox()
            // Minimal, broadly-supported tail. These avoid crashes on
            // constrained/gVisor/snap sandboxes without exotic flags. We avoid
            // flags like `--no-first-run`/`--no-default-browser-check` because
            // some snap Chromium wrappers reject them only when invoked
            // directly (non-shell).
            .arg("--disable-gpu")
            .arg("--disable-dev-shm-usage");

        // Resolve the Chromium/Chrome executable (explicit override, then
        // default PATH detection, substituting a wrapper for snap Chromium).
        if let Some(exe) = resolve_chrome_executable()? {
            builder = builder.chrome_executable(exe);
        }

        let config = builder.build().map_err(|e| anyhow::anyhow!(e))?;
        let (browser, mut handler) = Browser::launch(config).await?;

        let handler_task = tokio::spawn(async move {
            while handler.next().await.is_some() {}
        });

        let page = browser.new_page("about:blank").await?;

        Ok(Self {
            browser,
            page,
            _handler: handler_task,
        })
    }

    /// Navigate to a URL.
    pub async fn navigate(&self, url: &str) -> anyhow::Result<()> {
        self.page.goto(url).await?;
        Ok(())
    }

    /// Click an element matched by CSS selector.
    pub async fn click_selector(&self, selector: &str) -> anyhow::Result<()> {
        self.page.find_element(selector).await?.click().await?;
        Ok(())
    }

    /// Click at viewport coordinates (fallback when no selector is available).
    pub async fn click_point(&self, x: f64, y: f64) -> anyhow::Result<()> {
        self.page.click(Point::new(x, y)).await?;
        Ok(())
    }

    /// Type text into the element matched by `selector` (defaults to body).
    pub async fn type_text(&self, text: &str, selector: Option<&str>) -> anyhow::Result<()> {
        let sel = selector.unwrap_or("body");
        self.page
            .find_element(sel)
            .await?
            .click()
            .await?
            .type_str(text)
            .await?;
        Ok(())
    }

    /// Current page HTML (used as `current_context`).
    pub async fn content(&self) -> anyhow::Result<String> {
        Ok(self.page.content().await?)
    }

    /// Capture a PNG screenshot of the current page.
    pub async fn screenshot(&self) -> anyhow::Result<Vec<u8>> {
        let params = ScreenshotParams::builder().build();
        Ok(self.page.screenshot(params).await?)
    }

    /// Execute one neutral browser action and return the observed state.
    pub async fn execute(&self, action: &ActionResponse) -> anyhow::Result<ActionResult> {
        match action.action.as_str() {
            "navigate" => {
                let url = action
                    .params
                    .get("url")
                    .ok_or_else(|| anyhow::anyhow!("navigate requires 'url'"))?;
                self.navigate(url).await?;
            }
            "click" => {
                let x = action.params.get("x").and_then(|v| v.parse().ok());
                let y = action.params.get("y").and_then(|v| v.parse().ok());
                match (x, y) {
                    (Some(x), Some(y)) => self.click_point(x, y).await?,
                    _ => {
                        let sel = action
                            .params
                            .get("selector")
                            .ok_or_else(|| anyhow::anyhow!("click requires 'selector' or 'x'/'y'"))?;
                        self.click_selector(sel).await?;
                    }
                }
            }
            "type_text" => {
                let text = action
                    .params
                    .get("text")
                    .ok_or_else(|| anyhow::anyhow!("type_text requires 'text'"))?;
                let sel = action.params.get("selector").map(|s| s.as_str());
                self.type_text(text, sel).await?;
            }
            "extract_content" | "screenshot" => {
                // Observation-only actions; state is captured below.
            }
            other => anyhow::bail!("unsupported browser action: {other}"),
        }

        let screenshot = self.screenshot().await?;
        let context = self.content().await.unwrap_or_default();
        Ok(ActionResult { screenshot, context })
    }

    /// Close the browser and stop the handler task.
    pub async fn close(mut self) -> anyhow::Result<()> {
        self.browser.close().await?;
        Ok(())
    }
}
